#!/bin/sh

PROJECT_NAME="rrr"
TEST="meson test -C build"
RUN="./build/bin/$PROJECT_NAME"

command meson compile -C build

if [[ $1 == "test" ]]; then
  command $TEST 
else
  command $RUN
fi

return 0
