#!/bin/sh

PROJECT_NAME="rrr"
RUN="./bin/$PROJECT_NAME"
TEST="meson test
  navigation
  preview
  history
  command_line
  select
  -C build"

command meson compile -C build

if [[ $1 == "test" ]]; then
  command $TEST 
else
  cd build
  command $RUN
  cd ..
fi

return 0
